name: expense_management
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  go_router: ^14.8.0
  fl_chart: ^0.69.2
  shared_preferences: ^2.0.15
  intl: ^0.19.0
  qofi_comp:
    path: ../packages/qofi_comp
  #    git:
  #      url: https://github.com/khalils99/qofi_comp
  #      ref: main
  sizer: ^3.0.5
  encrypt: ^5.0.3
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.17
  pdf: ^3.11.2
  printing: ^5.14.0
  excel: ^4.0.6
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  open_filex: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mockito: ^5.2.0
flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/fonts/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.otf
        - asset: assets/fonts/Poppins/Poppins-Medium.otf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-SemiBold.otf
          weight: 700
