// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBexuk_BPbKmly0NLr45cPZAp7UAA4hthA',
    appId: '1:1049403455207:web:0b20a5133358dde65d1442',
    messagingSenderId: '1049403455207',
    projectId: 'expense-management-86663',
    authDomain: 'expense-management-86663.firebaseapp.com',
    storageBucket: 'expense-management-86663.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNu-q2C2wtr_8jID0C1ddsioHIIVxhO00',
    appId: '1:1049403455207:android:847daad0a11583f95d1442',
    messagingSenderId: '1049403455207',
    projectId: 'expense-management-86663',
    storageBucket: 'expense-management-86663.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4B_RJKHuujxdU0L8vvKqwkcYO8Nv5Xno',
    appId: '1:1049403455207:ios:b19437dc3d055ab15d1442',
    messagingSenderId: '1049403455207',
    projectId: 'expense-management-86663',
    storageBucket: 'expense-management-86663.firebasestorage.app',
    iosBundleId: 'com.app.expmanagement.expenseManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4B_RJKHuujxdU0L8vvKqwkcYO8Nv5Xno',
    appId: '1:1049403455207:ios:b19437dc3d055ab15d1442',
    messagingSenderId: '1049403455207',
    projectId: 'expense-management-86663',
    storageBucket: 'expense-management-86663.firebasestorage.app',
    iosBundleId: 'com.app.expmanagement.expenseManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBexuk_BPbKmly0NLr45cPZAp7UAA4hthA',
    appId: '1:1049403455207:web:5a2529186a252b5f5d1442',
    messagingSenderId: '1049403455207',
    projectId: 'expense-management-86663',
    authDomain: 'expense-management-86663.firebaseapp.com',
    storageBucket: 'expense-management-86663.firebasestorage.app',
  );
}
